package com.gx.po;

public class Power {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column power.powerId
	 * @mbggenerated  Mon Nov 06 14:52:45 CST 2017
	 */
	private Integer powerid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column power.userId
	 * @mbggenerated  Mon Nov 06 14:52:45 CST 2017
	 */
	private Integer userid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column power.powername
	 * @mbggenerated  Mon Nov 06 14:52:45 CST 2017
	 */
	private String powername;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table power
	 * @mbggenerated  Mon Nov 06 14:52:45 CST 2017
	 */
	public Power(Integer powerid, Integer userid, String powername) {
		this.powerid = powerid;
		this.userid = userid;
		this.powername = powername;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table power
	 * @mbggenerated  Mon Nov 06 14:52:45 CST 2017
	 */
	public Power() {
		super();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column power.powerId
	 * @return  the value of power.powerId
	 * @mbggenerated  Mon Nov 06 14:52:45 CST 2017
	 */
	public Integer getPowerid() {
		return powerid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column power.powerId
	 * @param powerid  the value for power.powerId
	 * @mbggenerated  Mon Nov 06 14:52:45 CST 2017
	 */
	public void setPowerid(Integer powerid) {
		this.powerid = powerid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column power.userId
	 * @return  the value of power.userId
	 * @mbggenerated  Mon Nov 06 14:52:45 CST 2017
	 */
	public Integer getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column power.userId
	 * @param userid  the value for power.userId
	 * @mbggenerated  Mon Nov 06 14:52:45 CST 2017
	 */
	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column power.powername
	 * @return  the value of power.powername
	 * @mbggenerated  Mon Nov 06 14:52:45 CST 2017
	 */
	public String getPowername() {
		return powername;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column power.powername
	 * @param powername  the value for power.powername
	 * @mbggenerated  Mon Nov 06 14:52:45 CST 2017
	 */
	public void setPowername(String powername) {
		this.powername = powername == null ? null : powername.trim();
	}
}