package com.gx.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import com.gx.po.User;
import com.gx.vo.RowCount;
import com.gx.vo.UserVo;

public interface UserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Mon Nov 06 14:52:45 CST 2017
	 */
	int deleteByPrimaryKey(Integer userid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Mon Nov 06 14:52:45 CST 2017
	 */
	int insert(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Mon Nov 06 14:52:45 CST 2017
	 */
	int insertSelective(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Mon Nov 06 14:52:45 CST 2017
	 */
	User selectByPrimaryKey(Integer userid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Mon Nov 06 14:52:45 CST 2017
	 */
	int updateByPrimaryKeySelective(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Mon Nov 06 14:52:45 CST 2017
	 */
	int updateByPrimaryKey(User record);
    
    /**
     * 自定义方法
     */
    List<User> findAll();
    
    @Select("select userId, username, password from user ${findBySQL}")
    List<User> findBySQL(@Param("findBySQL") String findBySQL);
    
    List<UserVo> findVoBySQL(@Param(value="findVoBySQL") String findVoBySQL);
    
    RowCount rowCount(@Param(value="findRowCountByVoSQL") String findRowCountByVoSQL);
    
    List<UserVo> findPageByVoSQL(@Param(value="findPageByVoSQL") String findPageByVoSQL, @Param("currentPage") Integer currentPage, @Param("pageSize") Integer pageSize);
    
}